"""empty message

Revision ID: b497b4c49240
Revises: 7f9186592782
Create Date: 2021-10-17 19:43:37.438164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b497b4c49240'
down_revision = '7f9186592782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('my_cart',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['name'], ['products.prod_name'], ),
    sa.ForeignKeyConstraint(['price'], ['products.price'], ),
    sa.PrimaryKeyConstraint('cart_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('my_cart')
    # ### end Alembic commands ###
